DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'amicable') THEN
        CREATE DATABASE "amicable";
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'POSTGRES_USER') THEN
        CREATE USER POSTGRES_USER WITH PASSWORD 'POSTGRES_PASSWORD';
    END IF;
END $$;

ALTER ROLE POSTGRES_USER
SET client_encoding TO 'utf8';
ALTER ROLE POSTGRES_USER
SET default_transaction_isolation TO 'read committed';
ALTER ROLE POSTGRES_USER
SET timezone TO 'Asia/Seoul';
GRANT ALL PRIVILEGES ON DATABASE "POSTGRES_DB" TO "POSTGRES_USER";

-- CREATE TABLE IF NOT EXISTS user ...