version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: amicable-api
    depends_on:
      - postgres
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:15.5-alpine3.18
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
